In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("weight-height.csv")

In [3]:
dataset

Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [4]:
dataset.columns

Index(['Gender', 'Height', 'Weight'], dtype='object')

In [5]:
dataset.info

<bound method DataFrame.info of       Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
...      ...        ...         ...
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]>

In [6]:
y = dataset["Weight"]

In [7]:
x = dataset["Height"]

In [8]:
x

0       73.847017
1       68.781904
2       74.110105
3       71.730978
4       69.881796
          ...    
9995    66.172652
9996    67.067155
9997    63.867992
9998    69.034243
9999    61.944246
Name: Height, Length: 10000, dtype: float64

In [9]:
y

0       241.893563
1       162.310473
2       212.740856
3       220.042470
4       206.349801
           ...    
9995    136.777454
9996    170.867906
9997    128.475319
9998    163.852461
9999    113.649103
Name: Weight, Length: 10000, dtype: float64

In [10]:
import numpy as np

In [11]:
info = np.vstack([x , y])  # merging two columns vertically

In [12]:
info

array([[ 73.84701702,  68.78190405,  74.11010539, ...,  63.86799221,
         69.03424313,  61.94424588],
       [241.89356318, 162.31047252, 212.74085556, ..., 128.47531878,
        163.85246135, 113.64910268]])

In [13]:
df_info = pd.DataFrame(info.T , columns=['weight' , 'Height'])  #  to add heading to the columns and view in a tabular format

In [14]:
df_info

weight      Height
0     73.847017  241.893563
1     68.781904  162.310473
2     74.110105  212.740856
3     71.730978  220.042470
4     69.881796  206.349801
...         ...         ...
9995  66.172652  136.777454
9996  67.067155  170.867906
9997  63.867992  128.475319
9998  69.034243  163.852461
9999  61.944246  113.649103

[10000 rows x 2 columns]

In [15]:
from sklearn.model_selection import train_test_split

C:\Users\ESHWAR\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [16]:
x_train , x_test , y_train , y_test = train_test_split(x , y , random_state=20)

In [17]:
pip install keras  

Note: you may need to restart the kernel to use updated packages.


In [18]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [19]:
from keras.models import Sequential

In [20]:
model = Sequential()

In [21]:
from keras.layers import Dense

In [22]:
model.get_config() # to view the configuration of the model. it includes details about the architecture of the model

# such as layers , theirt settings and other attributes that define the model

{'name': 'sequential', 'trainable': True, 'dtype': 'float32', 'layers': []}

In [23]:
model.summary() # provides summary of the architecture oc the neural network

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.add(
            Dense(
                    units=1 , # it means there is only one neuron in this Dense layer
                    activation="linear" , # determines the output of a neuron for the given input 
                    kernel_initializer="zeros" , # determines how the weights of the neurons in the layer are initialized
                    bias_initializer="zeros" , # determines how the bias terms of the neurons in the layer are initialized
                    input_shape=(1,)  # specifies the shape of the input data that the layers expects.
                 )
        )

C:\Users\ESHWAR\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [25]:
model.get_config()

{'name': 'sequential',
 'trainable': True,
 'dtype': 'float32',
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 1),
    'dtype': 'float32',
    'sparse': False,
    'name': 'input_layer'},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Dense',
   'config': {'name': 'dense',
    'trainable': True,
    'dtype': 'float32',
    'units': 1,
    'activation': 'linear',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    'kernel_constraint': None,
    'bias_constraint': None},
   'registered_name': None,
   'build_config': {'input_shape': (None, 1)}}],
 'build_input_shape': (None, 1)}

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 1)                   │               2 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.compile(loss = "mean_squared_error" , optimizer="Adam")  # it is used to configure the learning process of the model.
  #It specifies the loss function to use and the optimizer and any additional metrics to track during the training

In [28]:
model.get_weights()

[array([[0.]], dtype=float32), array([0.], dtype=float32)]

In [29]:
model.fit(x_train , y_train)

235/235 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25766.5703


In [30]:
model.get_weights()

[array([[0.22996153]], dtype=float32), array([0.22996406], dtype=float32)]

In [31]:
model.predict(100)

ValueError: Unrecognized data type: x=100 (of type <class 'int'>)

In [ ]:
# the model expect the input values of a particular shape in similar to the values of shapes we trained the model the model can 
# can predict the x_test values since we trained using the shape of x_train which are similar. So to find the shape of input 
# value to provide lets retrive a value from the set of values the model considers.

In [32]:
model.predict(x_test)

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([[14.6954  ],
       [17.189339],
       [15.024951],
       ...,
       [15.910308],
       [16.187103],
       [14.634572]], dtype=float32)

In [ ]:
# hence the model is considering the shape of x_test values so retrive a value from x_test to find its shape 
# we can retrieve a value from set using slicing operation

In [33]:
value = x_test[0:1] # retriveing the first value which has index value 0 and retrieving till the index value 1

In [34]:
value

9957    62.903719
Name: Height, dtype: float64

In [35]:
value.shape

(1,)

In [ ]:
# so the shape of an input value its considering is (1,) or also considered (1,1)

In [ ]:
# lets consider an input value as 100 and we convert its shape to (1,1)

In [36]:
input = 100

In [37]:
input = np.array([[100]]) # converting shape to (1,1)

In [38]:
input.shape

(1, 1)

In [39]:
model.predict(input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[23.226116]], dtype=float32)

In [ ]:
# so considering the shape of input the model predicted an outcome for an input value. But this model is not an ideal model
# here its a process or design for developing a model using neural networks. We create an ideal model adding all the parameters
# further

In [40]:
model.save("first_keras.h5")

In [41]:
model.get_layer("dense").input

<KerasTensor shape=(None, 1), dtype=float32, sparse=None, name=keras_tensor>

In [42]:
model.get_layer("dense").output

<KerasTensor shape=(None, 1), dtype=float32, sparse=False, name=keras_tensor_1>