In [1]:
from keras.datasets import mnist

C:\Users\ESHWAR\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
(x_train , y_train) , (x_test , y_test) = mnist.load_data()

In [3]:
len(x_train)

60000

In [4]:
len(x_test)

10000

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_train_1D = x_train.reshape(-1 , 28 , 28 , 1).astype("float32")

# here -1 represents no change in no.of individual samples ie.60000 , 28 , 28 are the height and width of the image pixel.
#1 refers no.of channels. here images are in single colour(grayscale) it have 1 and for RGB combined images it have3

In [7]:
x_train_1D

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [8]:
x_train_1D.shape

(60000, 28, 28, 1)

In [9]:
x_test_1D = x_test.reshape(-1 , 28 , 28 , 1).astype("float32")

In [10]:
x_test_1D.shape

(10000, 28, 28, 1)

In [11]:
from keras.utils import to_categorical

In [12]:
y_train_cat = to_categorical(y_train)

In [13]:
y_test_cat = to_categorical(y_test)

In [14]:
from keras.models import Sequential

In [15]:
model = Sequential()

In [16]:
model.get_config()

{'name': 'sequential', 'trainable': True, 'dtype': 'float32', 'layers': []}

In [19]:
from keras.layers import Convolution2D # Detects patterns or features in images such as edges , textures.
from keras.layers import MaxPooling2D    # Reduces the spatial dimensions ( height and width ) of the feature maps
from keras.layers import Flatten     # Converts multi-dimensional feature map into 1D vector to be fed into dense layesr
from keras.layers import Dense
from keras.layers import Dropout
from keras.regularizers import l2

In [18]:
model.add(
        Convolution2D(filters=20 , kernel_size=(5,5) , padding="same" , activation="relu" , input_shape = (28 , 28 , 1)))

C:\Users\ESHWAR\anaconda3\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
model.add(
        MaxPooling2D(pool_size=(2,2))
)

In [22]:
model.add(
        Convolution2D(filters=50 , kernel_size=(5,5) , padding="same" , activation="relu" , input_shape = (28 , 28 , 1)))

C:\Users\ESHWAR\anaconda3\lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [23]:
model.add(
        MaxPooling2D(pool_size=(2,2))
)

In [24]:
model.add(
        Flatten()
)

In [25]:
model.add(
        Dense(units=128 , activation="relu" , kernel_regularizer=l2(1e-5))
)

In [26]:
model.add(
        Dropout(0.5)
)

In [27]:
model.add(
        Dense(units=64 , activation="relu" , kernel_regularizer=l2(1e-5))
)

In [28]:
model.add(
        Dropout(0.5)
)

In [29]:
model.add(
        Dense(units=32 , activation="relu" , kernel_regularizer=l2(1e-5))
)

In [30]:
model.add(
        Dropout(0.5)
)

In [31]:
model.add(
        Dense(units=10 , activation="softmax" , kernel_regularizer=l2(1e-5))
)

In [32]:
model.get_config()

{'name': 'sequential',
 'trainable': True,
 'dtype': 'float32',
 'layers': [{'module': 'keras.layers',
   'class_name': 'InputLayer',
   'config': {'batch_shape': (None, 28, 28, 1),
    'dtype': 'float32',
    'sparse': False,
    'name': 'input_layer'},
   'registered_name': None},
  {'module': 'keras.layers',
   'class_name': 'Conv2D',
   'config': {'name': 'conv2d',
    'trainable': True,
    'dtype': 'float32',
    'filters': 20,
    'kernel_size': (5, 5),
    'strides': (1, 1),
    'padding': 'same',
    'data_format': 'channels_last',
    'dilation_rate': (1, 1),
    'groups': 1,
    'activation': 'relu',
    'use_bias': True,
    'kernel_initializer': {'module': 'keras.initializers',
     'class_name': 'GlorotUniform',
     'config': {'seed': None},
     'registered_name': None},
    'bias_initializer': {'module': 'keras.initializers',
     'class_name': 'Zeros',
     'config': {},
     'registered_name': None},
    'kernel_regularizer': None,
    'bias_regularizer': None,
    '

In [33]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 28, 28, 20)          │             520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d (MaxPooling2D)         │ (None, 14, 14, 20)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 14, 14, 50)          │          25,050 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_1 (MaxPooling2D)       │ (None, 7, 7, 50)            │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 2450)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         313,728 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 64)                  │           8,256 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 64)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_2 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │             330 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 349,964 (1.34 MB)

 Trainable params: 349,964 (1.34 MB)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.compile( loss= "categorical_crossentropy" , optimizer = "adam" , metrics=["accuracy"])

In [35]:
model.fit(x_train_1D , y_train_cat , epochs = 15 , validation_split=0.30 , batch_size = 100)

Epoch 1/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.1558 - loss: 3.5051 - val_accuracy: 0.4896 - val_loss: 1.4367
Epoch 2/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 17s 40ms/step - accuracy: 0.3633 - loss: 1.7068 - val_accuracy: 0.4996 - val_loss: 1.2894
Epoch 3/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 20s 46ms/step - accuracy: 0.4293 - loss: 1.4795 - val_accuracy: 0.5043 - val_loss: 1.2266
Epoch 4/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 20s 46ms/step - accuracy: 0.4602 - loss: 1.3585 - val_accuracy: 0.5047 - val_loss: 1.1823
Epoch 5/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 20s 48ms/step - accuracy: 0.4761 - loss: 1.2836 - val_accuracy: 0.5138 - val_loss: 1.1484
Epoch 6/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 21s 49ms/step - accuracy: 0.5209 - loss: 1.1778 - val_accuracy: 0.6023 - val_loss: 0.9373
Epoch 7/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 22s 52ms/step - accuracy: 0.5666 - loss: 1.0567 - val_accuracy: 0.6807 - val_loss: 0.7639
Epoch 8/15
420/420 ━━━━━━━━━━━━━━━━━━━━ 22s 53ms/step - accuracy: 0.6303 - loss: 0.8984 - 

In [36]:
model.evaluate(x_test_1D , y_test_cat , verbose=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8962 - loss: 0.2791


[0.2788699269294739, 0.8928999900817871]

In [37]:
model.evaluate(x_train_1D , y_train_cat , verbose=1)

1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 7ms/step - accuracy: 0.9006 - loss: 0.2388


[0.2585752606391907, 0.8957333564758301]

In [38]:
# accuracy and loss is much closer in testing and training evaluation which represents no overfitting during the training

In [39]:
x_test[:1].shape

(1, 28, 28)

In [40]:
model.predict(x_test_1D[3:4])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step


array([[0.39653265, 0.00190061, 0.00337736, 0.00525958, 0.00226066,
        0.17232732, 0.00428929, 0.00144338, 0.39147773, 0.02113138]],
      dtype=float32)

In [41]:
# considering above values as [1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 , 0]

In [42]:
y_test_cat[3:4]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
y_test[3:4]

array([0], dtype=uint8)

In [44]:
# lets write a code to predict the values and compare them with the cat values and the actual value.

In [53]:
import numpy as np
for j in range(5):
    prediction = model.predict(x_test_1D[j:j+1])
    prediction = np.array(prediction)
    binary_prediction = np.zeros_like(prediction)
    max_index = np.argmax(prediction)
    binary_prediction[0 , max_index] = 1
    print()
    print(f"Binary Prediction at index {j} is : \t \t [{binary_prediction.flatten()}]")
    print()
    cat_value = y_test_cat[j:j+1]
    actual_value = y_test[j:j+1]
    print(f"onehot - encoded value for index {j} is : \t {cat_value}")
    print()
    print(f"actual value for index {j} is : \t \t \t  {actual_value.flatten()} \n \n")
    print()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step

Binary Prediction at index 0 is : 	 	 [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]

onehot - encoded value for index 0 is : 	 [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]

actual value for index 0 is : 	 	 	  [7] 
 


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

Binary Prediction at index 1 is : 	 	 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

onehot - encoded value for index 1 is : 	 [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]

actual value for index 1 is : 	 	 	  [2] 
 


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

Binary Prediction at index 2 is : 	 	 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

onehot - encoded value for index 2 is : 	 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]

actual value for index 2 is : 	 	 	  [1] 
 


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step

Binary Prediction at index 3 is : 	 	 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

onehot - encoded value for index 3 is : 	 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

actual value for index 3 is : 	 	 	  [0] 
 


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step

Binary Prediction at 

In [ ]:
# the prediction of 5 values out of 5 are been correct in comparison to the cat and actual values. We can achive high accuracy 

# with the modifications in layers , regularizarion factor  , Dropout rate  , epochs and other impocting factors